### ISSUE TITLE
Module 1.2 Assignment

### ISSUE THREAD

**Issue by Mohammed-Shoaib** [Campus-Advisors/campus-advisor-training-Mohammed-Shoaib#2]
## Tasks

- [x] Create a directory using the command `mkdir`
- [x] In the directory you created initialize Git using `git init`
- [x] Create a README.md file in your directory using the `touch` command
- [x] Make sure README.md is in your _Working Directory_ by checking your status with `git status`
- [x] Move README.md from the _Working Directory_ to the _Staging Area_ by using `git add`
- [x] Make sure README.md is in your _Staging Area_ by checking your status with `git status`
- [x] Commit README.md to your repository using `git commit`
- [x] Make sure your _Working Directory_ and _Staging Area_ are clean with `git status`
- [x] Make sure your commit has been logged into your repository by using `git log`

### command line
![command line](https://user-images.githubusercontent.com/32389312/82450654-0a919c00-9abe-11ea-97a1-7dc521971065.png)

### git log
![git log](https://user-images.githubusercontent.com/32389312/82450670-0feee680-9abe-11ea-91d9-46b07223cca1.png)
