### ISSUE TITLE
Module 1.3 Assignment

### ISSUE THREAD

**Issue by Mohammed-Shoaib** [Campus-Advisors/campus-advisor-training-Mohammed-Shoaib#3]
## Tasks

- [x] Create a file called `campus_advisor.txt` in the directory you created in Module 1.2
- [x] Write "Hello Campus Advisors!" in `campus_advisor.txt` and **commit** your changes
- [x] Now write "Hola Campus Advisors!" in `campus_advisor.txt`
- [x] Show the differences between your _Working Directory_ and _Staging Area_
- [x] Add `campus_advisor.txt` to your _Staging Area_
- [x] Show the differences between your _Staging Area_ and your _Repository_
- [x] Commit campus_advisor.txt to your repository

### command line
![command line](https://user-images.githubusercontent.com/32389312/82524279-9697d800-9b3f-11ea-828f-2313985c9d88.png)

### git diff
![git diff](https://user-images.githubusercontent.com/32389312/82524285-9992c880-9b3f-11ea-91bb-b5efed8096a6.png)

### git diff --staged
![git diff --staged](https://user-images.githubusercontent.com/32389312/82524288-9bf52280-9b3f-11ea-8dbd-594aa988283b.png)

### git log
![git log](https://user-images.githubusercontent.com/32389312/82524291-9e577c80-9b3f-11ea-829b-a45569212916.png)
