### ISSUE TITLE
Module 1.4 Assignment

### ISSUE THREAD

**Issue by Mohammed-Shoaib** [Campus-Advisors/campus-advisor-training-Mohammed-Shoaib#4]
## Tasks

- [x] Go to [Visualizing Git](http://git-school.github.io/visualizing-git/)
- [x] Replicate the image above by determining the correct sequence of git commands
- [x] Take a screenshot of your work, including the command line, in the visualizer
- [x] Upload your screenshot to a new Issue titled Module 1.4 Assignment

### Visualizing Git
![visualizing git](https://user-images.githubusercontent.com/32389312/82524547-4cfbbd00-9b40-11ea-9c24-37817aed8f16.png)
