### ISSUE TITLE
Module 2.1 Assignment

### ISSUE THREAD

**Issue by Mohammed-Shoaib** [Campus-Advisors/campus-advisor-training-Mohammed-Shoaib#5]
# Module 2.1 Assignment

## Tasks

- [x] Copy the URL from the root of the repository
- [x] Clone the repository using `git clone <YOUR URL>`
- [x] Change directory to the repository by using the command `cd`
- [x] List the files by using the command `ls`

### command line

![command line](https://user-images.githubusercontent.com/32389312/82652795-45ffa800-9c2f-11ea-8696-a8af51e9ac36.png)
