### ISSUE TITLE
Module 2.2 Assignment

### ISSUE THREAD

**Issue by Mohammed-Shoaib** [Campus-Advisors/campus-advisor-training-Mohammed-Shoaib#6]
# Module 2.2 Assignment

## Tasks

- [x] Create a new branch called `edit-module-assignment` on GitHub.
- [x] On the `edit-module-assignment` branch, find this document, Module 2.2 Assignment and click the edit button.
- [x] In the editor for Module 2.2 Assignment add your name at the top of the document.
- [x] Scroll down and commit these changes.
- [x] On your local repository (on your computer) of the Campus-Advisor_Training repository, which we cloned in the last assignment, fetch and merge this change into your `master` branch on the command line.

### command line

![command line](https://user-images.githubusercontent.com/32389312/82656006-12734c80-9c34-11ea-9394-e183f15a43c0.png)

### git log from `edit-module-assignment` branch

![git log edit-module-assignment](https://user-images.githubusercontent.com/32389312/82656032-1acb8780-9c34-11ea-8222-b61a6b49b230.png)

### git log from `master` branch

![git log master](https://user-images.githubusercontent.com/32389312/82656043-2028d200-9c34-11ea-8804-91e2e79042d1.png)
